# Computational Environment {#sec:environment}

In this section, I will discuss the various computational environments you might
encounter. 
We'll also discuss some basic research tools that you'll need
to be successful in the lab, along with the philosophy behind each.

## Operating Systems

### Windows

### MacOS

### Linux
- [Quick introduction to Linux and why you should use it.](http://www.makeuseof.com/tag/whats-this-linux-thing-and-why-should-i-try-it/)
- [What is Linux, anyway?](http://beginlinux.wordpress.com/2009/03/25/what-is-linux-anyway/)
- [All-in-one guide to Ubuntu](http://www.ubuntupocketguide.com/)
- [Official Ubuntu Forums](http://www.ubuntuforums.org)
- [Ubuntu help/wiki pages.](https://help.ubuntu.com/)
- [Ubuntu wiki](https://wiki.ubuntu.com/)
- Infographics on hard drive layout of Ubuntu/Linux
    - [Infographic 1](http://imgur.com/EU6ga.jpg)
    - [Infographic 2](http://imgur.com/S5Ds2.jpg)
    - [More detailed information](http://www.ibm.com/developerworks/linux/library/l-lpic1-v3-102-1/index.html)
- Video Intro: An Intro to Linux
    - [Part 1: What is Linux?](https://www.youtube.com/watch?v=n0hM-5gSG3Y)
    - [Part 2: The Ubuntu Linux Live CD](https://www.youtube.com/watch?v=AqUfN5-7VQk)
- Interested in learning the power of command line? Invaluable collection of guides, commands and variables:
    - [Great site to learn CLI commands..](http://gd.tuwien.ac.at/linuxcommand.org/)
    - [Other great site for CLI](http://www.tuxfiles.org/linuxhelp/cli.html)
    - [Yet another CLI site. This site breaks the learning process down into lessons.](http://www.ee.surrey.ac.uk/Teaching/Unix/)
    - [FreeBSD in-browser emulator.](http://cb.vu/)
    - [Collection of Unix/Free-BSD/Linux commands. Great bookmark.](http://cb.vu/unixtoolbox.xhtml)
    - [Another collection of commands.](http://ss64.com/bash/) 
- Good sites/blogs to follow:
    - [Great collection of tutorials and guides. It's saved my butt more than once.](http://www.cyberciti.biz/faq/)
    - [Lifehacker tag "Linux"](http://lifehacker.com/tag/linux/)
    - [Lifehacker tag "Ubuntu"](http://lifehacker.com/tag/ubuntu/)
    - [Linux subreddit](http://www.reddit.com/r/linux)
    - [Ubuntu Geek](http://www.ubuntugeek.com)
    - [Ubuntu Tutorials](http://ubuntu-tutorials.com/)
    - [OMG Ubuntu](http://omgubuntu.co.uk/)
    - [Debian Admin](http://www.debianadmin.com)
- History of Linux/*nix (*nix is sometimes an abbreviation for Unix or Unix-like
  systems)
    - [Computer Hope](http://www.computerhope.com/history/unix.htm)
    - [Netfils](https://netfiles.uiuc.edu/rhasan/linux/)
    - [Living Internet](http://www.livinginternet.com/i/iw_unix_gnulinux.htm)
- Miscellaneous Links: 
    - [Ubuntu Installation Raid wiki](https://help.ubuntu.com/community/Installation/SoftwareRAID) 
    - [Salamander Linux](http://salamander-linux.com/)
    - [Easy to use RAID installer for Ubuntu.](http://www.reddit.com/r/linux/comments/bbatu/installing_ubuntu_with_raid_seems_too_complex_so/)
        - [Updated November 19th, 2013.](https://www.reddit.com/r/Ubuntu/comments/bbnkp/ive_tinkered_in_ubuntu_before_but_its_the_primary/c0lzpwk) 

### ChromeOS, etc.

I've never used ChromeOS and don't plan to anytime soon, so you're kind of on
your own here. Sorry!


## Command Line

### Shell Scripting

## Makefiles

## Plaintext Writing

### Vim

- [This is my favorite vim cheat sheet. Does anyone know who created it?](http://i.imgur.com/YLInLlY.png) - [[THREAD](https://www.reddit.com/r/vim/comments/32r85c/this_is_my_favorite_vim_cheat_sheet_does_anyone/)]

### Pandoc

### LaTeX

### Org Mode

## Citation Management

### Zotero

### Citations in Microsoft Word

### Citations in Latex (Bibtex)

### Citations in Pandoc / Org-Babel

## Version Control (Git and Github)

- [Git Resources](https://www.reddit.com/r/webdev/comments/9mddhg/i_use_git_for_my_own_internal_personal_projects/)

## Box.com

## SSH and Remote Access

## Center for Computational Research

## Project Organization

### Project Planning and Workflow

### References and Notes

### Virtualization / Containers

- [Open Source Infrastructure As Code Tutorial. Covers Packer, Ansible, Terraform, Docker, Kubernetes, Vagrant](https://www.reddit.com/r/homelab/comments/9uq6s7/open_source_infrastructure_as_code_tutorial/)
