# Machine Learning
## News
- [Google Deepmind moves to Tensorflow](http://googleresearch.blogspot.it/2016/04/deepmind-moves-to-tensorflow.html) - [[THREAD](https://www.reddit.com/r/Futurology/comments/4h4wwv/google_deepmind_moves_to_tensorflow/)]

## Learning Resources
### General
- [Gradient Boosting Explained](http://arogozhnikov.github.io/2016/06/24/gradient_boosting_explained.html)
- [P Need resources for xgboost + bayesian opt](https://www.reddit.com/r/MachineLearning/comments/9trtuk/d_need_resources_for_xgboost_bayesian_opt/)
- [Stanford's Deep Learning cheatsheet](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-deep-learning)
- [Understanding and Visualizing Neural Networks](https://www.youtube.com/watch?v=aircAruvnKk&t=337s) - [[THREAD](https://www.reddit.com/r/videos/comments/750j3m/understanding_and_visualizing_neural_networks/)]
- [What They Don’t Teach You in Machine Learning Courses](https://medium.com/taxify-labs/what-they-dont-teach-you-in-machine-learning-courses-53c936ccaacd)([thread](https://www.reddit.com/r/learnmachinelearning/comments/abtqv2/what_they_dont_teach_you_in_machine_learning/))
- [Deep Learning Tensorflow: Artificial & Convolutional Neural Networks, Artificial Intelligence Machine Learning In Python](https://medium.com/@martianba103/deep-learning-tensorflow-artificial-convolutional-neural-networks-artificial-intelligence-1c4d23f44fe7) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7rk4ck/deep_learning_tensorflow_artificial_convolutional/)]
- [A Simple Example To Learn Deconvolution And Locally Connected Deconvolution](https://github.com/microic/niy/tree/master/examples/girl_and_sunflower) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7oacjh/a_simple_example_to_learn_deconvolution_and/)]
- [Best seven books to check out in 2018 for Machine/Deep Learning and Medical Image Computing](http://www.mauricioreyes.me/blog/2018/01/05/best-seven-books-to-check-out-in-2018-for-machine-deep-learning-and-medical-image-computing/) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7obkbi/best_seven_books_to_check_out_in_2018_for/)]
- [Making Sentiment Analysis Easy With Scikit-Learn](https://twilioinc.wpengine.com/2017/12/sentiment-analysis-scikit-learn.html) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7ii2iq/making_sentiment_analysis_easy_with_scikitlearn/)]
- [Essential Guide to keep up with AI/ML/CV](https://github.com/BAILOOL/DoYouEvenLearn) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7h7grz/essential_guide_to_keep_up_with_aimlcv/)]
- [Basic Tutorial of Naive Bayes in python, Upvote the kaggle notebook if you find it useful](https://www.reddit.com/r/learnmachinelearning/comments/7h9b4h/basic_tutorial_of_naive_bayes_in_python_upvote/)
- [Machine Learning A-Z™: Hands-On Python & R In Data Science](https://www.linkedin.com/pulse/machine-learning-a-z-hands-on-python-r-data-science-sunil-kadam/?published=t) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7g5qxn/machine_learning_az_handson_python_r_in_data/)]
- [A-Z courses related to ML,AI,DS and DL](http://kuponshub.com/machine-learning-data-science-deep-learning-artificial-intelligence-a-z-courses/) - [[THREAD](https://www.reddit.com/r/learnmachinelearning/comments/7fnago/az_courses_related_to_mlaids_and_dl/)] 
- [Hamiltonian Monte Carlo Explained](http://arogozhnikov.github.io/2016/12/19/markov_chain_monte_carlo.html) ([thread](https://www.reddit.com/r/learnmachinelearning/comments/a379sf/mcmc_monte_carlo_explained_in_3d/))
- [PyTorch Autograd Explained In-depth with Graph Visuals](https://www.reddit.com/r/learnmachinelearning/comments/9tsw6s/pytorch_autograd_explained_indepth_with_graph/)
- [For Android developers getting into ML, I created a complete guide to building an app with a custom trained TensorFlow Lite model.](https://www.reddit.com/r/learnmachinelearning/comments/9ndkt2/for_android_developers_getting_into_ml_i_created/)
- [Making a training set for image classification](https://www.reddit.com/r/learnmachinelearning/comments/9i6j6n/making_a_training_set_for_image_classification/)

### Python
- [Multi-class confusion matrix library in Python](https://github.com/sepandhaghighi/pycm)

### Tensorflow
- [TensorFlow Tutorial | Deep Learning with TensorFlow | TensorFlow Tutorial for Beginners |Simplilearn](https://www.youtube.com/watch?v=_NMI8peAmNA)

### Deployment
- [Serving ML Quickly with TensorFlow Serving and Docker](https://medium.com/tensorflow/serving-ml-quickly-with-tensorflow-serving-and-docker-7df7094aa008?linkId=59087318)

## /r/machinelearning
- [D Faster R-CNN: Down the rabbit hole of modern object detection](https://tryolabs.com/blog/2018/01/18/faster-r-cnn-down-the-rabbit-hole-of-modern-object-detection/) - [THREAD]([https://www.reddit.com/r/MachineLearning/comments/7rcopi/d_faster_rcnn_down_the_rabbit_hole_of_modern/)
- [P Melanoma detection model](http://melanoma.modelderm.com) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7m7xp8/p_melanoma_detection_model/)]
- [P Why `tf.data` is so much better than `feed_dict` and how to build a simple data pipeline in 5 minutes.](https://www.reddit.com/r/MachineLearning/comments/a08fx6/d_why_tfdata_is_so_much_better_than_feed_dict_and/)
- [P Help with Deep Learning Workstation Configurations](https://www.reddit.com/r/MachineLearning/comments/a0g59s/d_help_with_deep_learning_workstation/)
- [[R] Large Scale GAN Training for High Fidelity Natural Image Synthesis . Includes a Colab Notebook of the implementation!! This is how it should be!!](https://www.reddit.com/r/MachineLearning/comments/9yer8h/r_large_scale_gan_training_for_high_fidelity/)
- [D Official Kaggle Learn - Interactive tutorials on Machine Learning, Deep Learning, R, and Data Visualization.](https://www.kaggle.com/learn/overview) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7qxjo3/d_official_kaggle_learn_interactive_tutorials_on/)]
- [D Easy intro to deploying ML into production](https://thehive.ai/blog/simple-ml-serving) - [THREAD]([https://www.reddit.com/r/MachineLearning/comments/7r5aef/d_easy_intro_to_deploying_ml_into_production/)
- [P Just put up an open source tool called Parris: a training tool for machine learning algorithms, made because I tire of recreating stacks over and over. Hope it helps!](https://github.com/jgreenemi/Parris) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7nesz7/p_just_put_up_an_open_source_tool_called_parris_a/)]
- [P Full graduate course in Bayesian ML [videos + slides + homework]](https://www.zabaras.com/statisticalcomputing) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7muyz2/d_full_graduate_course_in_bayesian_ml_videos/)]
- [[P] Aboleth - A bare-bones TensorFlow framework for Bayesian NNs](https://www.reddit.com/r/MachineLearning/comments/7kxsbp/p_aboleth_a_barebones_tensorflow_framework_for/)
- [P FloWaveNet: A Generative Flow for Raw Audio. PyTorch codes (also w/ ClariNet), sampled audio clips, and arXiv draft available](https://www.reddit.com/r/MachineLearning/comments/9uxbbj/p_flowavenet_a_generative_flow_for_raw_audio/)
- [[P] When to use Transfer Learning. Experimentation on different datasets in PyTorch](https://github.com/miguelgfierro/sciblog_support/blob/master/A_Gentle_Introduction_to_Transfer_Learning/Intro_Transfer_Learning.ipynb) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7ks2x4/p_when_to_use_transfer_learning_experimentation/)]
- [[R] Welcoming the Era of Deep Neuroevolution](https://eng.uber.com/deep-neuroevolution/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7knbip/r_welcoming_the_era_of_deep_neuroevolution/)]
- [P Tensorflow implementation of Curriculum Adaptive Sampling for Extreme Data Imbalance (MICCAI 2017) / LUNA16 Tutorial](https://github.com/taki0112/CASED-Tensorflow) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7l833k/p_tensorflow_implementation_of_curriculum/)]
- [[P] Survey of gradient based attribution/visualization techniques for deep learning models](http://blog.qure.ai/notes/deep-learning-visualization-gradient-based-methods) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7ksrwo/p_survey_of_gradient_based/)]
- [[D] How Do Machines Learn? - by CGPGrey](http://www.cgpgrey.com/blog/how-do-machines-learn) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7kms4i/d_how_do_machines_learn_by_cgpgrey/)]
- [[P] Data augmentation Random-Erasing](https://github.com/zhunzhong07/Random-Erasing) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7kq3q2/p_data_augmentation_randomerasing/)]
- [R Annotating Large Datasets with the TensorFlow Object Detection API](http://andrew.carterlunn.co.uk/programming/2018/01/24/annotating-large-datasets-with-tensorflow-object-detection-api.html) - [THREAD]([https://www.reddit.com/r/MachineLearning/comments/7smk47/r_annotating_large_datasets_with_the_tensorflow/)
- [PGenerating Inspirational quotes using Markov chains](https://medium.com/@ramtinalami/how-i-generated-inspirational-quotes-with-less-than-20-lines-of-code-38273623c905) -  [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7nix3e/pgenerating_inspirational_quotes_using_markov/)]
- [P Facebook AI Research Automatic Speech Recognition Toolkit](https://github.com/facebookresearch/wav2letter) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7nb5nq/p_facebook_ai_research_automatic_speech/)]
- [[P] Intro to Gaussian processes - Part I. For anyone who's after a more visual & intuitive primer on the topic.](http://bridg.land/posts/gaussian-processes-1) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7jkq2v/p_intro_to_gaussian_processes_part_i_for_anyone/)]
- [[D] Deep Learning for NLP, advancements and trends in 2017](https://tryolabs.com/blog/2017/12/12/deep-learning-for-nlp-advancements-and-trends-in-2017/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7jdtoy/d_deep_learning_for_nlp_advancements_and_trends/)]
- [[R] NIPS 2017 Notes - David Abel (Brown University)](https://cs.brown.edu/%7Edabel/blog/posts/misc/nips_2017.pdf) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7j9krt/r_nips_2017_notes_david_abel_brown_university/)]
- [[R] Deep Learning Scaling is Predictable, Empirically - Baidu Research](http://research.baidu.com/deep-learning-scaling-predictable-empirically/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7i8yhq/r_deep_learning_scaling_is_predictable/)]
- [[D] Glossary: Machine Learning Terminology For Beginners](https://sigmoidal.io/machine-learning-terms/?url) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7gf9i6/d_glossary_machine_learning_terminology_for/)]
- [[P] Parfit — hyper-parameter optimization with visualizations for Sklearn](https://medium.com/mlreview/parfit-hyper-parameter-optimization-77253e7e175e) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7g7q2l/p_parfit_hyperparameter_optimization_with/)]
- [[R] Population based training of neural networks | DeepMind](https://deepmind.com/blog/population-based-training-neural-networks/?source=techstories.org) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7g0liu/r_population_based_training_of_neural_networks/)]
- [[P] Tutorial: Making AI Art with Style Transfer using Keras](https://medium.com/mlreview/making-ai-art-with-style-transfer-using-keras-8bb5fa44b216) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7fofd7/p_tutorial_making_ai_art_with_style_transfer/)]
- [[P] Parametric tSNE implemented in Python using Tensorflow](https://github.com/jsilter/parametric_tsne) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7fnrjh/p_parametric_tsne_implemented_in_python_using/)]
- [[P] Image-Text-Embedding Using Dual-path ft CNN without RNN](https://github.com/layumi/Image-Text-Embedding) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7fajag/p_imagetextembedding_using_dualpath_ft_cnn/)]
- [[P] Tensorflow implementation of Graph Convolutional Network](https://github.com/shagunsodhani/pregel) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7f3y3r/p_tensorflow_implementation_of_graph/)]
- [[D] New Nature journal: Nature Machine Intelligence](https://www.reddit.com/r/MachineLearning/comments/7f0pkw/d_new_nature_journal_nature_machine_intelligence/)
- [[D] Optimization Algorithms: Math and Code](https://www.reddit.com/r/MachineLearning/comments/7ehxky/d_optimization_algorithms_math_and_code/)
- [[D] Fantastic GANs and where to find them II](http://guimperarnau.com/blog/2017/11/Fantastic-GANs-and-where-to-find-them-II) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7e2zis/d_fantastic_gans_and_where_to_find_them_ii/)]
- [[D] How to build a Portfolio as a Machine Learning/Data Science Engineer in industry ?](https://www.reddit.com/r/MachineLearning/comments/7dzh87/d_how_to_build_a_portfolio_as_a_machine/)
- [[D] A Cookbook for Machine Learning: a list of ML problem transformations and when to use them](http://www.inference.vc/design-patterns/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7dd45h/d_a_cookbook_for_machine_learning_a_list_of_ml/)]
- [A Visual Representation of Capsule Network Computations](https://medium.com/@mike_ross/a-visual-representation-of-capsule-network-computations-83767d79e737) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7cx9bv/a_visual_representation_of_capsule_network/)]
- [[P] PyTorch tutorials from MILA](https://github.com/mila-udem/welcome_tutorials/tree/master/pytorch) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7cw3ts/p_pytorch_tutorials_from_mila/)]
- [[R] A Reinforcement Learning primer - Everything You Need to Know to Get Started in RL](https://joshgreaves.com/reinforcement-learning/introduction-to-reinforcement-learning/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7cgoyg/r_a_reinforcement_learning_primer_everything_you/)]
- [[D] Lot of misconceptions around capsules network?](https://www.reddit.com/r/MachineLearning/comments/7cf7ba/d_lot_of_misconceptions_around_capsules_network/)
- [[R] Understanding Deep Learning: The Information Bottleneck Connection](https://weberna.github.io/jekyll/update/2017/11/08/Information-Bottleneck-Part1.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7cbzo6/r_understanding_deep_learning_the_information/)]
- [[D] 7 Takeaways from MLconf SF](https://towardsdatascience.com/7-takeaways-from-mlconf-sf-1b2703db5ecb) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7c9zci/d_7_takeaways_from_mlconf_sf/)]
- [[N] Deep|Bayes – Summer School on Deep Learning and Bayesian Methods](http://deepbayes.ru/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7c8i0h/n_deepbayes_summer_school_on_deep_learning_and/)]
- [[N] SpaCy 2.0 released (Natural Language Processing with Python)](https://github.com/explosion/spaCy/releases/tag/v2.0.0) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7bn8e8/n_spacy_20_released_natural_language_processing/)]
- [[P] Using Deep Learning for Single Image Super Resolution (with a live demo)](https://blog.deepsense.ai/using-deep-learning-for-single-image-super-resolution/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/7ays7r/p_using_deep_learning_for_single_image_super/)]
- [[D] The State of ML and Data Science 2017](https://www.kaggle.com/surveys/2017) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/79p4v0/d_the_state_of_ml_and_data_science_2017/)]
- [[P] The often-overlooked random forest kernel](https://rmarcus.info/blog/2017/10/04/rfk.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/79ajuf/p_the_oftenoverlooked_random_forest_kernel/)]
- [[P] How We Built an AI to Play SNES Street Fighter II Turbo](https://medium.com/gyroscopesoftware/how-we-built-an-ai-to-play-street-fighter-ii-can-you-beat-it-9542ba43f02b) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/78nec1/p_how_we_built_an_ai_to_play_snes_street_fighter/)]
- [[D] Deep Learning Book companion videos](https://youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/77sp6s/d_deep_learning_book_companion_videos/)]
- [[N] gradient decent , how neural networks learn , part 2](https://youtu.be/IHZwWFHWa-w) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/76rt3z/n_gradient_decent_how_neural_networks_learn_part_2/)]
- [[P] Flappy Bird using Deep Q Networks in Tensorflow.](https://github.com/hardikbansal/Qlearning/tree/master/Flappy) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/76iycp/p_flappy_bird_using_deep_q_networks_in_tensorflow/)]
- [[D] Attention in Neural Networks and How to Use It](http://akosiorek.github.io/ml/2017/10/14/visual-attention.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/76j5lo/d_attention_in_neural_networks_and_how_to_use_it/)]
- [[R] Bayesian Nonparametrics: Dirichlet process and its applications](https://blog.statsbot.co/bayesian-nonparametrics-9f2ce7074b97) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/75x75f/r_bayesian_nonparametrics_dirichlet_process_and/)]
- [[P] A rock-paper-scissors machine built on TensorFlow](https://cloud.google.com/blog/big-data/2017/10/my-summer-project-a-rock-paper-scissors-machine-built-on-tensorflow) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/762msh/p_a_rockpaperscissors_machine_built_on_tensorflow/)]
- [[R] 2 Hr. Talk "Information Theory of Deep Learning" (Naftali Tishby)](https://www.youtube.com/watch?v=RKvS958AqGY) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/75uua6/r_2_hr_talk_information_theory_of_deep_learning/)]
- [[N] Deep RL Bootcamp 2017 - Slides and Talks](https://sites.google.com/view/deep-rl-bootcamp/lectures) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/75i2us/n_deep_rl_bootcamp_2017_slides_and_talks/)]
- [[P] Visualising Activation Functions in Neural Networks](https://dashee87.github.io/data%20science/deep%20learning/visualising-activation-functions-in-neural-networks/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/75aimu/p_visualising_activation_functions_in_neural/)]
- [[P] Sequence Pair Classification in TensorFlow using Sequence-Semantic-Embeddings (SSE)](https://github.com/eBay/Sequence-Semantic-Embedding) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/74vf5g/p_sequence_pair_classification_in_tensorflow/)]
- [[R] GANs are Broken in More Than One Way: review of "The Numerics of GANs"](http://www.inference.vc/my-notes-on-the-numerics-of-gans/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/74g8ee/r_gans_are_broken_in_more_than_one_way_review_of/)]
- [[N] It's here! "But what \*is\* a Neural Network? | Deep learning, Part 1](https://youtu.be/aircAruvnKk) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/74gual/n_its_here_but_what_is_a_neural_network_deep/)]
- [[D] New Theory Cracks Open the Black Box of Deep Learning](https://www.quantamagazine.org/new-theory-cracks-open-the-black-box-of-deep-learning-20170921/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/71pfwn/d_new_theory_cracks_open_the_black_box_of_deep/)]
- [[R] Matterport3D Research Dataset: a massive set of labeled 3D scans of buildings, and what it enables](https://medium.com/@llebttam_45762/announcing-the-matterport3d-research-dataset-815cae932939) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/71le4t/r_matterport3d_research_dataset_a_massive_set_of/)]
- [[N] NIPS Workshop on Machine Learning for Creativity and Design](https://nips2017creativity.github.io) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/706sz6/n_nips_workshop_on_machine_learning_for/)]
- [Data Science Interview Questions](http://www.learndatasci.com/data-science-interview-questions) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/701dqo/data_science_interview_questions/)]
- [[P] Gradient Trader Part 1: The Surprising Usefulness of Autoencoders](http://rickyhan.com/jekyll/update/2017/09/14/autoencoders.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/702jcy/p_gradient_trader_part_1_the_surprising/)]
- [[R] Guide on building your own neural conversational agent](https://blog.statsbot.co/chatbots-machine-learning-e83698b1a91e) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6znm1j/r_guide_on_building_your_own_neural/)]
- [[P] VAE with VGG loss for celebA](https://github.com/yzwxx/vae-celebA) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6z2o4c/p_vae_with_vgg_loss_for_celeba/)]
- [[P] PyTorch and Pytorch tricks for Kaggle competitions (Amazon satellite image comp)](https://www.reddit.com/r/pytorch/comments/6z0yeo/pytorch_and_pytorch_tricks_for_kaggle/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6z0zlo/p_pytorch_and_pytorch_tricks_for_kaggle/)]
- [[Research] Using very deep autoencoders for collaborative filtering](https://github.com/NVIDIA/DeepRecommender) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6yzcjd/research_using_very_deep_autoencoders_for/)]
- [[P] TensorFlow Agents: Efficient Batched Reinforcement Learning in TensorFlow](https://github.com/tensorflow/agents) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6yzzyu/p_tensorflow_agents_efficient_batched/)]
- [[P] Pseudo-labeling a simple semi-supervised learning method](https://datawhatnow.com/pseudo-labeling-semi-supervised-learning/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6ysvpy/p_pseudolabeling_a_simple_semisupervised_learning/)]
- [[P] Creative Applications of Deep Learning with TensorFlow Python package](http://github.com/pkmital/pycadl) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/6yauct/p_creative_applications_of_deep_learning_with/)]
- [[Project] Torch implementation of Image-to-Image translation using Conditional Adversarial Nets](https://github.com/phillipi/pix2pix) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5exqp4/project_torch_implementation_of_imagetoimage/)]
- [[P] Tutorial: Image Classification and Segmentation using Tensorflow and TF-Slim.](https://www.reddit.com/r/MachineLearning/comments/5edvpk/p_tutorial_image_classification_and_segmentation/)
- [[News] Deep Learning by Ian Goodfellow & Yoshua Bengio has officially shipped](https://www.amazon.com/gp/product/0262035618/ref=ya_st_dp_summary) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5edfuh/news_deep_learning_by_ian_goodfellow_yoshua/)]
- [[P] Interactive visualization by Google of recent paper by Hardt, Srebro and Price about fair machine learning](http://research.google.com/bigpicture/attacking-discrimination-in-ml/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5e27ec/p_interactive_visualization_by_google_of_recent/)]
- [[Discussion] Using CNNs for fluid flow analysis](https://www.reddit.com/r/MachineLearning/comments/5d70it/discussion_using_cnns_for_fluid_flow_analysis/)
- [[R] Composing graphical models with neural networks - NIPS 2016 spotlight video](https://www.youtube.com/watch?v=btr1poCYIzw) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5d12wf/r_composing_graphical_models_with_neural_networks/)]
- [[Discussion] Reinforcement Learning lectures by David Silver from DeepMind](https://www.youtube.com/playlist?list=PLwQyV9I_3POuVsyB3hCyl3Iieb1oWVfPP) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5d1lzt/discussion_reinforcement_learning_lectures_by/)]
- [[Research] Hierarchical Object Detection with Deep Reinforcement Learning (in Keras)](https://imatge-upc.github.io/detection-2016-nipsws/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5cvea4/research_hierarchical_object_detection_with_deep/)]
- [[Project] Interactive deep convolutional networks features visualization for Keras](https://jakebian.github.io/quiver/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5cv5ks/project_interactive_deep_convolutional_networks/)]
- [[P] A collection of minimal and clean implementations of machine learning algorithms](https://github.com/rushter/MLAlgorithms) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5cqdh5/p_a_collection_of_minimal_and_clean/)]
- [[R] "Learning Curve Prediction With Bayesian Neural Networks", Klein et al 2016 (hyperparameter optimization)](http://openreview.net/pdf?id=S11KBYclx) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5bvvhw/r_learning_curve_prediction_with_bayesian_neural/)]
- [[P] CNN for Human Activity Recognition in Tensorflow](http://aqibsaeed.github.io/2016-11-04-human-activity-recognition-cnn/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5b9hg6/p_cnn_for_human_activity_recognition_in_tensorflow/)]
- [[R] Highway and Residual Networks learn Unrolled Iterative Estimation](http://openreview.net/forum?id=Skn9Shcxe) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5b7w82/r_highway_and_residual_networks_learn_unrolled/)]
- [Neural Enhance: Super Resolution for images](https://github.com/alexjc/neural-enhance) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/59zs0t/neural_enhance_super_resolution_for_images/)]
- [DeepTeach: the interactive deep image classifier builder](http://blog.mldb.ai/blog/posts/2016/10/deepteach) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/58blab/deepteach_the_interactive_deep_image_classifier/)]
- [[R] Introducing the AI Open Network: a 100% open-source AI research community.](http://ai-on.org/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5863cq/r_introducing_the_ai_open_network_a_100/)]
- [[P] An Introduction to Statistical Learning with Applications in R (book, pdf)](http://www-bcf.usc.edu/~gareth/ISL/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/57mzou/p_an_introduction_to_statistical_learning_with/)]
- [[Project] How to Use t-SNE Effectively](http://distill.pub/2016/misread-tsne/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/57gios/project_how_to_use_tsne_effectively/)]
- [[Project] A TensorFlow implementation of DeepMind's WaveNet paper](https://github.com/ibab/tensorflow-wavenet) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/56ml9j/project_a_tensorflow_implementation_of_deepminds/)]
- [GPU-accelerated Theano & Keras on Windows 10 native [UPDATED TO Keras1.1.0 + Theano0.8.2 + VS2015 + CUDA8.0 + cuDNN5.1]](https://www.reddit.com/r/MachineLearning/comments/562iyr/gpuaccelerated_theano_keras_on_windows_10_native/)
- [TensorFlow in a Nutshell - Part Three: All the Models](https://medium.com/@camrongodbout/tensorflow-in-a-nutshell-part-three-all-the-models-be1465993930#.qaxeqvl90) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/55puyn/tensorflow_in_a_nutshell_part_three_all_the_models/)]
- [Tensorflow Code: CNN on Graphs with Fast Localized Spectral Filtering](https://github.com/mdeff/cnn_graph) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/55j6dk/tensorflow_code_cnn_on_graphs_with_fast_localized/)]
- [Alternating Back-Propagation for Generator Network](http://www.stat.ucla.edu/~ywu/ABP/main.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/55e33g/alternating_backpropagation_for_generator_network/)]
- [A Neural Network for Machine Translation, at Production Scale](https://research.googleblog.com/2016/09/a-neural-network-for-machine.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/54ta0m/a_neural_network_for_machine_translation_at/)]
- [TensorFlow tutorial (extensive) with Kaggle competition, used by Nvidia, FFN, CNN, RNN, Kaggle, AE](https://github.com/alrojo/tensorflow-tutorial) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/53trbb/tensorflow_tutorial_extensive_with_kaggle/)]
- [Build a TensorFlow Image Classifier in 5 Min](https://www.youtube.com/watch?v=QfNvhPx5Px8&feature=youtu.be) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/5219fd/build_a_tensorflow_image_classifier_in_5_min/)]
- [Single notebook VAE-GAN hybrid tutorial/demo. Multi-gpu, latent space algebra, spike-triggered avg. style receptive fields, etc.](https://github.com/timsainb/Tensorflow-MultiGPU-VAE-GAN) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/51xnmf/single_notebook_vaegan_hybrid_tutorialdemo/)]
- [How to make Keras+Theano use Nvidia GPUs with Optimus under Ubuntu 16.04](https://github.com/fisadev/docs/blob/master/keras_nvidia_optimus_ubuntu.rst) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/51yg9f/how_to_make_kerastheano_use_nvidia_gpus_with/)]
- [Phd-level courses](https://www.reddit.com/r/MachineLearning/comments/51qhc8/phdlevel_courses/)
- [Deep Learning with Python and Tensorflow (Ian Lewis)](https://www.youtube.com/watch?v=U0ACP9J8vOU) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4zxzzh/deep_learning_with_python_and_tensorflow_ian_lewis/)]
- [Image Super-Resolution With a DCGAN - Github](https://github.com/david-gpu/srez) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4zuybx/image_superresolution_with_a_dcgan_github/)]
- [Deep Learning with Keras - Tutorial @ EuroScipy 2016](https://github.com/leriomaggio/deep-learning-keras-euroscipy2016) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4zpnl0/deep_learning_with_keras_tutorial_euroscipy_2016/)]
- [Deep Learning Summer School, Montreal 2016 - VideoLectures](http://videolectures.net/deeplearning2016_montreal/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4zcpg3/deep_learning_summer_school_montreal_2016/)]
- [An introduction to Matrix Factorization, Factorization Machine and Field-aware Factorization Machine](http://www.kemaswill.com/uncategorized/from-matrix-factorization-to-factorization-machines/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4xa5yu/an_introduction_to_matrix_factorization/)]
- [Deep Learning with Neural Networks and TensorFlow Tutorials](https://www.reddit.com/r/MachineLearning/comments/4uj4t4/deep_learning_with_neural_networks_and_tensorflow/)
- [The Open Source Society has created a solid path for you that want to learn Data Science and Machine Learning, online for free as a github repo.](https://github.com/open-source-society/data-science) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4q238x/the_open_source_society_has_created_a_solid_path/)]
- [16 Free Machine Learning Books](https://hackerlists.com/free-machine-learning-books/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4oczzy/16_free_machine_learning_books/)]
- [Machine Learning is Fun: A simple explanation of how image recognition works using python and tflearn](https://medium.com/@ageitgey/machine-learning-is-fun-part-3-deep-learning-and-convolutional-neural-networks-f40359318721#.4qpabvx3i) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4nzb01/machine_learning_is_fun_a_simple_explanation_of/)]
- [A Gentle Introduction to the Basics of Machine Learning](https://miguelgfierro.com/blog/2016/a-gentle-introduction-to-the-basics-of-machine-learning/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4mnrsx/a_gentle_introduction_to_the_basics_of_machine/)]
- [Convolution by Evolution: DeepMind publishes a paper about its framework to mix DL and evolutionary algorithms](http://mlanctot.info/files/papers/gecco16-dppn.pdf) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4mck0y/convolution_by_evolution_deepmind_publishes_a/)]
- [Introducing our Hybrid lda2vec Algorithm](http://multithreaded.stitchfix.com/blog/2016/05/27/lda2vec/#topic=38&lambda=1&term=) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4lvbcl/introducing_our_hybrid_lda2vec_algorithm/)]
- [Morphing Faces - variational autoencoder](http://vdumoulin.github.io/morphing_faces/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4lfayd/morphing_faces_variational_autoencoder/)]
- [Introducing our Hybrid lda2vec Algorithm](http://multithreaded.stitchfix.com/blog/2016/05/27/lda2vec) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4lbwxx/introducing_our_hybrid_lda2vec_algorithm/)]
- [The International Conference on Learning Representations (ICLR) 2016 talks are now on http://videolectures.net](http://videolectures.net/iclr2016_san_juan/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4lb50u/the_international_conference_on_learning/)]
- [Voxel-Based Variational Autoencoder Demonstration](https://www.youtube.com/watch?v=LtpU1yBStlU) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4lbu88/voxelbased_variational_autoencoder_demonstration/)]
- [Those of you using ML in production, what does your tech stack look like? [May 2016]](https://www.reddit.com/r/MachineLearning/comments/4l1376/those_of_you_using_ml_in_production_what_does/)
- [TensorFlow Fizzbuzz](http://joelgrus.com/2016/05/23/fizz-buzz-in-tensorflow/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4kp658/tensorflow_fizzbuzz/)]
- [Theano implementation of Tree RNNs aka Recursive Neural Networks](https://github.com/ofirnachum/tree_rnn) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4k1hk6/theano_implementation_of_tree_rnns_aka_recursive/)]
- [Building Autoencoders in Keras](http://blog.keras.io/building-autoencoders-in-keras.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4jgwfx/building_autoencoders_in_keras/)]
- [Guide to setting up your machine for deep learning from scratch (Ubuntu)](https://github.com/saiprashanths/dl-setup) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4jbqkc/guide_to_setting_up_your_machine_for_deep/)]
- [100 Machine Learning videos you can't find in Google](https://www.youtube.com/channel/UCjeM1xxYb_37bZfyparLS3Q/videos) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4j7ft5/100_machine_learning_videos_you_cant_find_in/)]
- [In-depth Machine Learning Course w/ Python](https://www.reddit.com/r/MachineLearning/comments/4j0u2z/indepth_machine_learning_course_w_python/)
- [Train a convolutional net for smile detection in less than a minute (Keras, Jupyter Notebook)](https://github.com/kylemcdonald/SmileCNN) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4ib167/train_a_convolutional_net_for_smile_detection_in/)]
- [Introduction to Recurrent Networks in TensorFlow](http://danijar.github.io/introduction-to-recurrent-networks-in-tensorflow) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4hzjmy/introduction_to_recurrent_networks_in_tensorflow/)]
- [A curated list of awesome TensorFlow experiments, libraries, and projects. Inspired by awesome-machine-learning.](https://github.com/jtoy/awesome-tensorflow/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4hkbh5/a_curated_list_of_awesome_tensorflow_experiments/)]
- [A Friendly Introduction to Cross-Entropy Loss [OC]](http://rdipietro.github.io/friendly-intro-to-cross-entropy-loss/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4hkbn4/a_friendly_introduction_to_crossentropy_loss_oc/)]
- [How to quantize neural networks with TensorFlow](https://petewarden.com/2016/05/03/how-to-quantize-neural-networks-with-tensorflow) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4hm0ds/how_to_quantize_neural_networks_with_tensorflow/)]
- [DeepMind moves to TensorFlow](http://googleresearch.blogspot.co.uk/2016/04/deepmind-moves-to-tensorflow.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4h030r/deepmind_moves_to_tensorflow/)]
- [What is your opinion on Coursera 'Statistics with R' specialization ?](https://www.reddit.com/r/MachineLearning/comments/4g9oeq/what_is_your_opinion_on_coursera_statistics_with/)
- [TensorFlow Introductory Lecture](https://www.reddit.com/r/MachineLearning/comments/4fwnjf/tensorflow_introductory_lecture/)
- [An Interactive Node-Link Visualization of Convolutional Neural Networks](http://scs.ryerson.ca/~aharley/vis/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4fcvzd/an_interactive_nodelink_visualization_of/)]
- [Free ebook on Machine Learning for Recommender Systems](http://subhrajitroy.com/machine-learning-for-recommender-systems-ebook/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4e6aex/free_ebook_on_machine_learning_for_recommender/)]
- [[Keras] Simple tutorial on Visual Question Answering on Jupyter Notebook - data/model included [OC]](http://iamaaditya.github.io/2016/04/visual_question_answering_demo_notebook) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4dh3h3/keras_simple_tutorial_on_visual_question/)]
- [Pastalog: Simple, realtime visualization of neural network training performance for Python and more](https://github.com/rewonc/pastalog) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4diqkb/pastalog_simple_realtime_visualization_of_neural/)]
- [GloVe Word Embedding in theano](https://github.com/shashankg7/glove-theano) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4cwy7s/glove_word_embedding_in_theano/)]
- [Deep Learning Tutorial Series for NLP: Lesson 1 – A Single Neuron - Thoughtly](http://www.thoughtly.co/blog/deep-learning-lesson-1/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4cs7sc/deep_learning_tutorial_series_for_nlp_lesson_1_a/)]
- [TFLearn: Higher-level API for TensorFlow](https://github.com/tflearn/tflearn) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4cqtw7/tflearn_higherlevel_api_for_tensorflow/)]
- [Music Language Modeling with Recurrent Neural Networks in TensorFlow](http://yoavz.com/music_rnn/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4ctd55/music_language_modeling_with_recurrent_neural/)]
- [How to work with large JSON datasets using Python and Pandas](https://www.dataquest.io/blog/using-json-data-in-pandas/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4c4kcb/how_to_work_with_large_json_datasets_using_python/)]
- [Misleading modelling: overfitting, cross-validation, and the bias-variance trade-off (Python)](http://blog.cambridgecoding.com/2016/03/24/misleading-modelling-overfitting-cross-validation-and-the-bias-variance-trade-off/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4bxxob/misleading_modelling_overfitting_crossvalidation/)]
- [Theano Tutorial](http://www.marekrei.com/blog/theano-tutorial/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4b36rk/theano_tutorial/)]
- [Scikit-learn Tutorial - PyCon NYC 2015](https://github.com/jakevdp/sklearn_pycon2015) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4b3jhv/scikitlearn_tutorial_pycon_nyc_2015/)]
- [Whiskey Embeddings](http://wrec.herokuapp.com/methodology) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/4aii29/whiskey_embeddings/)]
- [How to Code and Understand DeepMind's Neural Stack Machine (in Python)](https://iamtrask.github.io/2016/02/25/deepminds-neural-stack-machine/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/47znuh/how_to_code_and_understand_deepminds_neural_stack/)]
- [NLM Pill Image Recognition Challenge (\$25k Prize)](http://pir.nlm.nih.gov/challenge/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/46gxog/nlm_pill_image_recognition_challenge_25k_prize/)]
- [Here is a tutorial on Restricted Boltzmann Machines](http://xiangjiang.live/2016/02/12/a-tutorial-on-restricted-boltzmann-machines/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/45llly/here_is_a_tutorial_on_restricted_boltzmann/)]
- [Detecting Outliers In High Dimensional Data Sets](http://shahramabyari.com/2016/01/19/detecting-outliers-in-high-dimensional-data-sets/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/41sul3/detecting_outliers_in_high_dimensional_data_sets/)]
- [OpenFace 0.2.0: Higher accuracy and halved execution time.](http://bamos.github.io/2016/01/19/openface-0.2.0/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/41o99y/openface_020_higher_accuracy_and_halved_execution/)]
- ["Recognizing and Localizing Endagered Right Whale with Extremely Deep Neural Networks"](http://felixlaumon.github.io/2015/01/08/kaggle-right-whale.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/40hluu/recognizing_and_localizing_endagered_right_whale/)]
- [TensorFlow is Terrific – A Sober Take on Deep Learning Acceleration](http://www.kdnuggets.com/2015/12/tensor-flow-terrific-deep-learning-library.html) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3znrls/tensorflow_is_terrific_a_sober_take_on_deep/)]
- [TensorFlow: a new LSTM RNN based Morse decoder experiment](https://www.reddit.com/r/MachineLearning/comments/3yhjry/tensorflow_a_new_lstm_rnn_based_morse_decoder/)
- [5 important Python Data Science advancements of 2015](https://medium.com/@elgehelge/the-5-most-important-python-data-science-advancements-of-2015-a136482da89b#.k8lxrh842) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3wupq5/5_important_python_data_science_advancements_of/)]
- [TensorFlow Tutorial with notebooks and code examples](https://github.com/aymericdamien/TensorFlow-Examples) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3ta27b/tensorflow_tutorial_with_notebooks_and_code/)]
- [Anyone Can Learn To Code an LSTM-RNN in Python (Part 1: RNN)](http://iamtrask.github.io/2015/11/15/anyone-can-code-lstm/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3szfsn/anyone_can_learn_to_code_an_lstmrnn_in_python/)]
- [NVIDIA Deep Learning Course](https://www.youtube.com/playlist?list=PL5B692fm6--tI-ijknnVZWbXU2H4JpSYe) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3sy1ao/nvidia_deep_learning_course/)]
- [Learning Stats and Probability with \#python notebooks](https://github.com/rouseguy/intro2stats) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3ozg99/learning_stats_and_probability_with_python/)]
- [Eigenstyle - Principal Component Analysis and Fashion](http://blog.thehackerati.com/post/126701202241/eigenstyle) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3hf6k7/eigenstyle_principal_component_analysis_and/)]
- [Drawing with GoogLeNet](http://auduno.com/post/125837418083/drawing-with-googlenet) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3fqp6t/drawing_with_googlenet/)]
- [Database of Labelled Data for AI Research](https://www.reddit.com/r/MachineLearning/comments/3fd7jy/database_of_labelled_data_for_ai_research/)
- ["Basics of Computational Reinforcement Learning" by Michael Littman at RLDM 2015](http://videolectures.net/rldm2015_littman_computational_reinforcement/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3fcjj0/basics_of_computational_reinforcement_learning_by/)]
- [Tutorial on "Deep Reinforcement Learning" by David Silver at RLDM 2015](http://videolectures.net/rldm2015_silver_reinforcement_learning/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3fcjfj/tutorial_on_deep_reinforcement_learning_by_david/)]
- [Complete Course on Machine Learning (Spring 2015) at CMU by Alex Smola - (Fully Tagged and Searchable)](http://www.computervisiontalks.com/tag/machine-learning-class-10-701/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3dzgb4/complete_course_on_machine_learning_spring_2015/)]
- [Must Watch Python for Data Science Videos from SciPy Conference 2015, Austin, Texas (From /r/Python)](http://www.analyticsvidhya.com/blog/2015/07/data-science-videos-scipy-2015/) - [[THREAD](https://www.reddit.com/r/MachineLearning/comments/3dn9b4/must_watch_python_for_data_science_videos_from/)]
