# Overview

## Dry Lab vs. Wet Lab {#subsec:dry-lab-vs-wet-lab}

For starters, this is a dry lab. This means that we don't do any benchwork -- no
pipettes, no cell cultures, no tissue collection or cutting or fixing or
staining. About 95% of what we do is on the computer, phone, pen-and-paper, or
whiteboard. 

We do perform some image acquisition in the form of whole-slide scanning; it
would be useful to sit down with the head of our digital imaging core ([Dr. Amber
Worral](mailto:aworral@buffalo.edu)) and the head of the microscopy core ([Dr.
Wade Sigurdson](mailto:wsj@buffalo.edu)) to understand how our data is
generated. I'll go over some of that here as well.

## Meetings and Schedule {#subsec:meetings-and-schedule}

Our lab houses students at every academic level, from high school through
post-doc. I recognize that you have classes and jobs and whatnot outside of the
lab, and I will be accommodating. Having said that, I do have some basic,
reasonable expectations of your time committment.

Occasionally missing meetings or being absent from the lab for exams and classes
is fine as long as you communicate with me.  However, if you catagorically
cannot commit to at least this level of participation, it will be very difficult
for you to make significant progress on your project.  
 
Because of this, **I will not accept graduate students who cannot meet this
schedule**. Undergraduate volunteers have more leeway, but there needs to be a
clear discussion about your role and expected progress.

At a minimum, I meet with all students at least **twice a week**, once for a 1-2
hour face-to-face meeting and again for a 1 hour weekly "all-hands" lab meeting.
Outside of that, you will be expected to work in the lab space you are provided
whenever possible.

### One-on-One Meetings

One-on-one meetings allow me to see your work in a private setting, give honest
critical feedback, and help to come up with the next steps for your project.
**Come prepared**, with notes from our last meeting, examples of your work and
updates, as well as any problems or concerns from last time. I will run down the
list and ask for status updates before we dive into some next things to work on. 

### Lab Meetings

Lab meetings are where everyone can learn about what's going on in the lab. We
do practice presentations for conferences, review posters and papers, and talk
about new tools or programs that we may want to use in the lab, as well
as establishing lab priorities and upcoming events.

### Lab Working Space

**Whether we have a scheduled meeting or not**, it is expected that you will be
able to work in the lab space you are provided. There are a number of reasons:

- You can interact with your labmates and ask them for help if needed;
- You should be available for impromptu meetings, as often happens;
- I need to justify the space our lab has been given in JSMBS, or *we will lose
  it*;
- Almost all students are more productive working in the lab than from home. I
  know it's *theoretically* possible to work from home, and it's sometimes
  necessary during crunch times, but I have yet to see this work as a long-term
  strategy -- and this includes my own personal experience.

## Lab Notebooks and Record-Keeping

All students **MUST** keep a lab notebook. It's up to you whether this is a
pen-and-paper notebook or one that is online. Each have their pros and cons:

### Pen and Paper

------------------------------------------------------------------
**Pros**                          **Cons** 
--------------------------------  --------------------------------
Easy to carry and use             Not searchable

Never runs out of batteries       Not backed up (scanned pages?)

Write what/how ever you want      Need an additional physical item

Faster than typing[^f1]           Code, output, plots, imgs are hard

Quiet, less obtrusive 

----------------------------  ----------------------------

: Pros and Cons of pen-and-paper lab notebooks.

[^f1]: Depends on typing speed

### Electronic

We'll talk more about these in the research [tools
section](#sec:research-tools), but as a shorthand, the benefits and drawbacks of
electronic notebooks are the inverse of those for physical notebooks.

------------------------------------------------------------------
**Pros**                          **Cons** 
--------------------------------  --------------------------------
Always backed up                  Need to keep it charged

Searchable                        Easy to get distracted

Accessible on most devices        Can be difficult to keep up

Cut-and-paste code, images, etc.  Dependent on workflow / software

------------------------------------------------------------------

: Pros and cons of electronic lab notebooks. 

## Lab Conduct

### Professional Conduct

### Academic Standing and Integrity


## Diversity and Inclusion

The lab is designed to be a diverse and inclusive environment for everyone who
wants to do good scientific work. Apart from professional conduct, I believe
it is important to take active steps to promote diversity throughout our careers
in any way that we can. To that end, here are some resources to assist in
creating an inclusive and welcoming environment. 

### Actionable Resources

Below is a list of "Actionable Resources", i.e. things you can do to promote
diversity in the workplace. A lot of these are focused on the tech industry (and
on middle-managers), but they are good guidelines for being an advocate for
diversity in STEM in general, and at any stage of your career.

---

[5 Ally Actions | June 15, 2018 - By Better
  Allies](https://code.likeagirl.io/5-ally-actions-june-15-2018-cfdef1e590cb)

*Use inclusive language, such as "partner" or "spouse" versus "wife" or
"husband."*

I don't believe that simple language or behavioral changes will lead to greater
acceptance, or in creating an inclusive environment. However, I think that it's
important to recognize how your speech may sound to others. The way you speak is
influenced by the way you think, and your words can have unintended
consequences. When someone tells you that the words you use are unwelcome or
make them uncomfortable, take that information seriously. 

*Don't evaluate candidates solely on their Github portfolio*

This is specific to hiring managers for software engineers, but the point is
that you shouldn't evaluate someone based on things that require luxury free
time or hobbies. Some folks -- like those who are working multiple jobs, or
single parents -- may not have the free time to participate in extra-curricular
activities. This extends to social events as well.

*Give stretch assignments*

Don't patronize. The way to allow your students to develop is to challenge and
push them beyond what they thought they could accomplish. To that end, give them
challenging work and assistance if they need it. Most importantly, give them the
credit when they complete the assignment, and take the responsibility if they
cannot.

*Mentor a person of color*

This works for all levels -- make sure that you are promoting the work your
colleagues are doing. Not only is networking and interpersonal infamy an
invaluable avenue for future jobs, it's also a way to show your co-workers that
you respect what they do.  Give your honest praise to their work; it's not
enough to merely appreciate it from afar, you need to be vocal to others about
what they're doing.

*Don't assume good intent*

It's very common to try to find an explanation for behavior that avoids
uncomfortable feelings on race, gender identity, religion, or sexual preference.
But trying to avoid this discomfort is dismissing the actual discomfort that
victims of bias feel about the behavior. Don't try to explain away behavior
because you are uncomfortable about where the conversation is headed. Trust that
your co-workers know when they are being offended, and that their feelings are
legitimate, and that sometimes offense WAS intended.

---

[10 Actionable Ways To Actually Increase Diversity In Tech - By Catherine
Ashcraft](https://www.fastcompany.com/3041339/10-commitments-that-will-make-a-difference-in-increasing-diversity-in-tec)

1. We will keep the focus on changing company culture and avoid focusing
   only or primarily on the "pipeline"
2. We will demonstrate top leadership support and accountability
3. We will involve "majority-group" members in change efforts
4. We will ensure an ongoing commitment to reporting and tracking the data
5. We will expand the kinds of data we collect
6. We will help managers learn to reduce unconscious biases
7. We will analyze job descriptions, recruitment strategies, and interview
   practices for hidden biases.
8. We will consciously develop and sponsor highly qualified underrepresented
   talent
9. We will ensure productive team environments where all members can contribute
   to innovation and problem solving
10. We will implement flexible work-life policies and make it okay to actually
    use these policies without overt or subtle repercussions

---

[Bias and Hiring: How We Hire UX Researchers - By Sharon
Bautista](https://medium.com/firefox-ux/bias-and-hiring-how-we-hire-ux-researchers-6f9db9f8d670)

Firefox User Research team is hiring; this article details the steps the
hiring team went through to modify their hiring pratices to address bias
and unfairness in the system.

**Old System**

- Mozilla recruiter screens resumes for basic work requirements (legal status,
high-level relevant work experience)
- Phone screen to verify HR reqs, applicant's reqs, work history, relevant
  experience
- 2 research team members conduct individual phone screens to understand
  experience level, work with distributed teams
- Invite to Mozilla office for 1:1 in-person interviews with researchers and
  non-researchers and asked to present a research exercise

*Pros:*

- Involved both researchers and those who interact with researchers
- Mix of remote and in-person components reflect work at Mozilla
- Yielded good results

*Cons:*

- Questions were determined by interviewers
- Staff entered unstructured notes into applicant tracking system
- Inconsistent use of notes in final decision-making meetings

**New System**

*The Process:*

- Document current hiring practices explicitly to identify areas of improvement
- Learn as much as possible about bias in hiring
    - [Clayman Institute for Gender Research](https://gender.stanford.edu/)
- Developed a list of essential and desired criteria for job candidates
- Criteria were discussed in detail to make expectations explicit rather than
  implicit
    - "1-3 years experience" changed to "1-3 years of industry experience"
- Wrote out phone and interview questions that aligned with criteria
- Developed a rubric for grading answers to the questions, plus example
  "excellent", "acceptable", and "poor" answers
- Determined at what phase of hiring process each question could be asked
- Modified research exercise to make its purpose and constraints more explicit,
  also with detailed rubric for the exercise
- Developed worksheets that staff can use to document the answers, as well as
  any additional questions posed to applicants (and questions the candidates
  ask)
- Documents are linked to the tracking system and be used to structure the
  decision-making meetings

*Anticipated Benefits:*

- Less bias on the hiring team about desirable candidates
- Less time spent screening resumes with established criteria
- Less time preparing for and processing interviews
- Flexibility to add new questions, but more attention to how questions are
  tracked and answers documented
- Less time on final decision making given the criteria, rubrics, and explicit
  expectations

The template used for hiring is here:
[https://docs.google.com/spreadsheets/d/1KNpcSPTnoSOPsIaRjTu9zaqtSA5-W5l3wxYBAcakHVk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1KNpcSPTnoSOPsIaRjTu9zaqtSA5-W5l3wxYBAcakHVk/edit?usp=sharing)

---

[On Improving Diversity in
Hiring](https://cate.blog/2017/09/28/on-improving-diversity-in-hiring/).

**Inclusion First**

> Inclusion needs to come first. Don't hire people into an environment they
> can't be successful in. 

- Identify "types" of people you need to have to be successful
- Are these characteristics necessary, and could someone who does not possess
  those qualities work at your institution?
- Would those people be successful if you hired them?
- Does your hiring, environment, or promotion process prioritize people with
  different types of personalities?

> A good rule for inclusion pre-work to diversity is to stop doing things you
> would have to change if the demographics of your team better reflected the
> demographics of the world.

**On-boarding**

- How long does it take someone to be ramped up and productive?
- Prioritize on-boarding, as it's hard to fix later
- Evaluate teams based on their ability to support newbies, not teams that are
  struggling for experienced experts.

**Juniors**

- Ask whether your team is healthy enough to onboard someone without much
  experience
- Consider that if this is someone's first job, a massive failure could impact
  whether they remain in the field

**Diversity as Performance Art**

- Give workers recognition for work they actually do -- what they are paid for
  -- rather than their status as under-represented. 
- See also: [Diversity as Performance Art](https://cate.blog/2016/12/01/diversity-as-performance-art/): 
  >  Inclusion is what you do when you show up every day.
- Diversity as performance art stops at hiring
- It doesn't change the economics, or the underlying culture

**Mentoring**

- Mentoring is about building relationships, even if they aren't people who work
  for or with you


---

[If you think women in tech is just a pipeline problem, you haven't been paying
attention](https://medium.com/tech-diversity-files/if-you-think-women-in-tech-is-just-a-pipeline-problem-you-haven-t-been-paying-attention-cb7a2073b996)

---

[Bootstrapping Inclusion - By Jason
Wong](http://www.attack-gecko.net/2017/10/22/bootstrapping-inclusion/)

Finding diverse candidates is easy, but it's the wrong problem. The real problem
is existing sexist, racism, and anti-LGBTQ sentiment -- in other words, it's
not just about hiring diverse workers, it's about supporting them once they get there. 
