# Programming {#sec:programming}
## Python
### Introduction

Python is a very popular language thanks to it's simple construction, gigantic
user community, and wide coverage of packages that allow you to do all kinds of
interesting things. 

Here are some basic features of Python as a programming language:

- It is an **interpreted** language, meaning that the source code (the programs
  you write) are executed as-is without first compiling into an executable file
  (e.g. a file ending in `.exe` on Windows).
- It is **dynamically typed**, meaning that the code can adapt at runtime to
  encompass different variable types, object definitions, and code extensions. 
- It is **garbage-collected**, meaning that you do not have to worry (too much)
  about the low-level memory maps of the computer. 

These make it less optimized in terms of memory and execution speed compared
with lower-level compiled languages like C++.  However, this is more than
compensated for by the large user community, increased source-code readability,
and science-focused packages that we'll be making use of in the lab.

### Installation

In our lab, we use the [Anaconda](https://www.anaconda.com/distribution/) distribution of Python. 

### Resources
- [A guide to creating animated 3-D data visualizations in Python](http://geoffboeing.com/2015/04/animated-3d-plots-python/) - [[THREAD](https://www.reddit.com/r/visualization/comments/32lgj8/a_guide_to_creating_animated_3d_data/)]

### Jupyter Notebook
- [Jupyter Notebook | Installation, User Interface Tour, Complete Walkthrough](https://www.youtube.com/watch?v=sYH0LECSKSA&feature=share)

### Data Visualization
- [Visualising countries' debt-to-gdp ratio. A visualisation tutorial with Plotly and Python](http://richard-muir.com/blog/2016/09/19/exploring-gdp-growth-rate-and-debt-to-gdp-ratio/) - [[THREAD](https://www.reddit.com/r/visualization/comments/55pfbs/visualising_countries_debttogdp_ratio_a/)]
- [Visualizing chaos with data sets that are self-similar and fractal, using IPython notebook + matplotlib](http://geoffboeing.com/2015/03/chaos-theory-logistic-map/) - [[THREAD](https://www.reddit.com/r/visualization/comments/30iedb/visualizing_chaos_with_data_sets_that_are/)]
- [How to make beautiful data visualizations in Python with matplotlib](http://www.randalolson.com/2014/06/28/how-to-make-beautiful-data-visualizations-in-python-with-matplotlib/) - [[THREAD](https://www.reddit.com/r/visualization/comments/2vrrcj/how_to_make_beautiful_data_visualizations_in/)]
- [How to Generate FiveThirtyEight Graphs in Python](https://www.dataquest.io/blog/making-538-plots/) - [[THREAD](https://www.reddit.com/r/visualization/comments/6yy5z4/how_to_generate_fivethirtyeight_graphs_in_python/)]

## Matlab

## R
- [Using program R's package dplyr to clean and organize large datasets. [x-post from r/rstats]](https://ecologicalrelationships.wordpress.com/2016/09/07/using-rs-dplyr-to-clean-and-manipulate-your-data/) - [[THREAD](https://www.reddit.com/r/DataHoarder/comments/51ntk3/using_program_rs_package_dplyr_to_clean_and/)]
- [Free and Open Source Materials for a short course on Statistics and Visualisation with R. Link is to one of the animations produced in the course and course materials are in linked in the description of the video (including annotated code).](https://youtu.be/mIDuPWqu0_4) - [[THREAD](https://www.reddit.com/r/visualization/comments/3emvyn/free_and_open_source_materials_for_a_short_course/)]

### Data Visualization
- [R + ggplot2 Graph Catalog](http://shinyapps.stat.ubc.ca/r-graph-catalog/) - [[THREAD](https://www.reddit.com/r/visualization/comments/2unq9j/r_ggplot2_graph_catalog/)]
- [R graph gallery](http://flowingdata.com/2016/10/25/r-graph-gallery/) - [[THREAD](https://www.reddit.com/r/visualization/comments/59a53d/r_graph_gallery/)]
- [A Course for Visualization in R, Taking You From Beginner to Advanced](http://flowingdata.com/2015/05/06/introducing-a-course-for-visualization-in-r/) - [[THREAD](https://www.reddit.com/r/visualization/comments/369ayz/a_course_for_visualization_in_r_taking_you_from/)]
- [An Introduction on How to Make Beautiful Charts With R and ggplot2](http://minimaxir.com/2015/02/ggplot-tutorial/) - [[THREAD](https://www.reddit.com/r/visualization/comments/2vnzi4/an_introduction_on_how_to_make_beautiful_charts/)]

## Web (HTML, Javascript, CSS, etc.)
